language: ruby
rvm:
  - 2.3.0
sudo: false
script: RUBYOPT=W0 bundle exec rake test
before_script:
  - gem install bundler
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/actionmailer42.gemfile
  - test/gemfiles/actionmailer41.gemfile
  - test/gemfiles/actionmailer40.gemfile
  - test/gemfiles/actionmailer32.gemfile
